# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.4

EAPI=6

CRATES="
aho-corasick-0.6.4
backtrace-0.3.4
backtrace-sys-0.1.16
cargo_metadata-0.4.0
cc-1.0.3
cfg-if-0.1.2
dbghelp-sys-0.2.0
derive-new-0.5.0
diff-0.1.11
dtoa-0.4.2
env_logger-0.4.3
error-chain-0.11.0
getopts-0.2.15
itoa-0.3.4
kernel32-sys-0.2.2
lazy_static-1.0.0
libc-0.2.34
log-0.3.8
memchr-2.0.1
num-traits-0.1.41
quote-0.3.15
regex-0.2.3
regex-syntax-0.4.1
rustc-demangle-0.1.5
rustfmt-nightly-0.3.4
semver-0.8.0
semver-parser-0.7.0
serde-1.0.24
serde_derive-1.0.24
serde_derive_internals-0.18.0
serde_json-1.0.8
syn-0.11.11
synom-0.11.3
term-0.4.6
thread_local-0.3.5
toml-0.4.5
unicode-segmentation-1.2.0
unicode-xid-0.0.4
unreachable-1.0.0
utf8-ranges-1.0.0
void-1.0.2
winapi-0.2.8
winapi-build-0.1.1
"

inherit cargo

DESCRIPTION="Tool to find and fix Rust formatting issues"
HOMEPAGE="https://github.com/rust-lang-nursery/rustfmt"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="Apache-2.0/MIT" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
